# -*- coding: utf-8 -*-
"""Nasa_Covid.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1R1FEsh6kIWlb8mQvGhUtoVIE4h12Fm6f

# Diase Predictions
"""

# Montar o drive para que o nosso script consiga acessar a base de dados.
from google.colab import drive
drive.mount('/content/drive')

import os
os.chdir("/content/drive/My Drive/nasaspaceapps")  #MAPEAR PARA O LOCAL NO DRIVE ONDE SE ENCONTRA ESSE ARQUIVO

!ls #Ver a localização desse script nas pastas. o ARQUIVO DEVE ESTAR LISTADO ABAIXO

"""# Setup

##Importar bibliotecas necessárias
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# %matplotlib inline

df = pd.read_csv('Nasa_challenge.csv')

df.head()

#coluna rótulo: 'País'
# número de Países:
len(df)

"""Tratando vaoleres faltantes"""

df.describe()

df = df.fillna(df.mean())
df.describe()

df.shape

"""Configurando o algorítimo KNN"""

X = df.iloc[:,0:5]
y = df.iloc[:,10]

X.head()

y.head()

X_train, X_test, y_train, y_test = train_test_split(X,y,test_size=0.3)

knn = KNeighborsClassifier(n_neighbors=9)

knn = knn.fit(X_train, y_train)

y_pred = knn.predict(X_test)

accuracy_score(y_test,y_pred)